#! /usr/bin/env python3


'''Create static webpages from a template.'''


DEBUG = False


import sys
import buildwebpagelib as bw


def main(args):
    '''Build the webpage.

    :param args: command-line arguments
    :type  args: list of str

    '''
    try:
        settings = bw.get_settings(args[1:])
        webpage = bw.Webpage(settings)
        webpage.build_webpage()
    except Exception as error:
        if DEBUG:
            import traceback
            traceback.print_exc()
        else:
            sys.stderr.write('Error: ' + str(error) + '\n')


if __name__ == '__main__':
    main(sys.argv)
