#! /usr/bin/env python


'''Create webpages from a template.'''
# TODO better doc


VERSION = '1.0-rc1'


import sys

import buildwp.cli
import buildwp.webpage


def main(args):
    '''Build the webpage.
    
    :param args: command-line arguments
    :type  args: list of str
    
    '''
    settings = buildwp.cli.Settings(args[1:])
    webpage = buildwp.webpage.Webpage(settings)
    webpage.build_webpage()


if __name__ == '__main__':
    main(sys.argv)
